import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../model/doctor.dart';
import '../provider/doctor_provider.dart';

class AddDoctorFormView extends ConsumerWidget {
  const AddDoctorFormView({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final GlobalKey<FormState> formKey = GlobalKey<FormState>();
    final TextEditingController nameController = TextEditingController();
    final TextEditingController specializationController =
        TextEditingController();
    final TextEditingController contactNumberController =
        TextEditingController();
    final TextEditingController emailController = TextEditingController();
    return Scaffold(
      appBar: AppBar(title: Text('Add New Doctor')),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Form(
          key: formKey,
          child: Column(
            spacing: 16.0,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const Text('Fill in the details below to add a new doctor.'),
              const Divider(),
              const SizedBox(height: 16.0),
              TextFormField(
                controller: nameController,
                decoration: InputDecoration(labelText: 'Doctor Name'),
              ),
              TextFormField(
                controller: specializationController,
                decoration: InputDecoration(labelText: 'Specialization'),
              ),
              TextFormField(
                controller: contactNumberController,
                decoration: InputDecoration(labelText: 'Contact Number'),
              ),
              TextFormField(
                controller: emailController,
                decoration: InputDecoration(labelText: 'Email Address'),
              ),
              ElevatedButton(
                onPressed: () async {
                  if (formKey.currentState?.validate() ?? false) {
                    final doctor = Doctor(
                      id: '', // ID will be generated by Firestore
                      name: nameController.text,
                      specialty: specializationController.text,
                      phoneNumber: contactNumberController.text,
                      email: emailController.text,
                    );
                    final result = await ref.read(
                      addDoctorProvider(doctor).future,
                    );
                    if (!context.mounted) return; // Guard with mounted check
                    if (result.isSuccess) {
                      // Success handling
                      ref.refresh(
                        getAllDoctorsProvider,
                      ); // Refresh the doctors list
                      ScaffoldMessenger.of(context).showSnackBar(
                        SnackBar(content: Text('Doctor added successfully')),
                      );
                    } else {
                      // Error handling
                      ScaffoldMessenger.of(context).showSnackBar(
                        SnackBar(
                          content: Text('Error: ${result.errorMessage}'),
                        ),
                      );
                    }
                    // Clear the form fields after submission
                    formKey.currentState?.reset();
                  }
                },
                child: const Text('Add Doctor'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class EditDoctorFormView extends ConsumerWidget {
  final Doctor doctor;

  const EditDoctorFormView({super.key, required this.doctor});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final GlobalKey<FormState> formKey = GlobalKey<FormState>();
    final TextEditingController nameController = TextEditingController(
      text: doctor.name,
    );
    final TextEditingController specializationController =
        TextEditingController(text: doctor.specialty);
    final TextEditingController contactNumberController = TextEditingController(
      text: doctor.phoneNumber,
    );
    final TextEditingController emailController = TextEditingController(
      text: doctor.email,
    );

    return Scaffold(
      appBar: AppBar(title: Text('Edit Doctor Details')),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Form(
          key: formKey,
          child: Column(
            spacing: 16.0,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const Text('Update the details below and save changes.'),
              Divider(),
              const SizedBox(height: 16.0),
              TextFormField(
                controller: nameController,
                decoration: InputDecoration(labelText: 'Doctor Name'),
              ),
              TextFormField(
                controller: specializationController,
                decoration: InputDecoration(labelText: 'Specialization'),
              ),
              TextFormField(
                controller: contactNumberController,
                decoration: InputDecoration(labelText: 'Contact Number'),
              ),
              TextFormField(
                controller: emailController,
                decoration: InputDecoration(labelText: 'Email Address'),
              ),
              ElevatedButton(
                onPressed: () async {
                  if (formKey.currentState?.validate() ?? false) {
                    final updatedDoctor = doctor.copyWith(
                      name: nameController.text,
                      specialty: specializationController.text,
                      phoneNumber: contactNumberController.text,
                      email: emailController.text,
                    );
                    final result = await ref.read(
                      updateDoctorProvider(updatedDoctor).future,
                    );
                    if (!context.mounted) return; // Guard with mounted check
                    if (result.isSuccess) {
                      // Success handling
                      ref.refresh(
                        getAllDoctorsProvider,
                      ); // Refresh the doctors list
                      ScaffoldMessenger.of(context).showSnackBar(
                        SnackBar(content: Text('Doctor updated successfully')),
                      );
                    } else {
                      // Error handling
                      ScaffoldMessenger.of(context).showSnackBar(
                        SnackBar(
                          content: Text('Error: ${result.errorMessage}'),
                        ),
                      );
                    }
                  }
                },
                child: const Text('Save Changes'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
